require 'helper'
# used for storing private data like google account_id
require 'local_conf' if File.exists?('local_conf.rb')

class TestSatellite < Test::Unit::TestCase

  should "create a proper google adapter" do
    tracker = Satellite.get_tracker(:google_analytics)
    assert_equal tracker.type, Satellite::Adapters::GoogleAnalytics
  end

  should "return any created tracker as tracker interface" do
    tracker = Satellite.get_tracker(:google_analytics)
    assert_equal tracker.class, Satellite::TrackerInterface
  end

  context 'google_adapter' do

    #http://www.google-analytics.com/__utm.gif?
    #utmwv=5.1.5&
    #utms=1&
    #utmn=595987258&
    #utmhn=www.chinaseo.com&
    #utme=8(customVarTest*customVarTest)9(Sorry%20for%20bothering*Sorry%20for%20bothering)11(1*1)&
    #utmcs=UTF-8&
    #utmsr=1440x900&
    #utmsc=24-bit&
    #utmul=de&
    #utmje=1&
    #utmfl=10.3%20r183&
    #utmdt=Demo%20Of%20Google%20Analytics%20Event%20Tracking&
    #utmhid=1655425535&
    #utmr=http%3A%2F%2Fwww.google.de%2Fsearch%3Fsourceid%3Dchrome%26ie%3DUTF-8%26q%3Dgoogle%2Bevent%2Btracking%2Bdemo&
    #utmp=%2Fseo-tips%2F6-seo-tips%2F21-demo-of-google-analytics-event-tracking.html&
    #utmac=UA-9543667-1&
    #utmcc=__utma%3D222620745.1505395584.1314029203.1314029203.1314094748.2%3B%2B__utmz%3D222620745.1314094748.2.2.utmcsr%3Dgoogle|utmccn%3D(organic)|utmcmd%3Dorganic|utmctr%3Dgoogle%2520event%2520tracking%2520demo%3B&
    #utmu=D~
    should "properly track a page view" do
      tracker = Satellite.get_tracker(:google_analytics, {
          :utms => 1,
          #:utmn => 123456789, autogenerated
          :utmhn => 'api.mymobai.com',
          :utme => '5(controller*action*coupon_redeem)(10)8(test)9(Please_track_this)11(1)',
          :utmcn => 1,
          :utmcs => 'UTF-8',
          :utmsr => '1440x900',
          :utmul => 'de',
          :utmje => '1',
          :utmfl => '10.3%20r183',
          :utmdt => 'Properly track a page view',
          #:utmhid => '1655425535', auto
          :utmr => 'test.local/properly track a page view',
          :utmp => '/test/properly-track-page-view',
          :utmac => GOOGLE_ACCOUNT_ID
      })
      
      assert_equal tracker.track_page_view, true
    end
  end
end
