require 'helper'
# used for storing private data like google account_id
require 'local_conf' if File.exists?('local_conf.rb')

class TestSatellite < Test::Unit::TestCase

  should "create a proper google adapter" do
    tracker = Satellite.get_tracker(:google_analytics)
    assert_equal tracker.type, Satellite::Adapters::GoogleAnalytics
  end

  should "return any created tracker as tracker interface" do
    tracker = Satellite.get_tracker(:google_analytics)
    assert_equal tracker.class, Satellite::TrackerInterface
  end

  context 'google_adapter' do

    #http://www.google-analytics.com/__utm.gif?
    #utmwv
    #utms
    #utmn
    #utmhn
    #utme
    #utmcs
    #utmsr
    #utmsc
    #utmul
    #utmje
    #utmfl
    #utmdt=
    #utmhid
    #utmr
    #utmp
    #utmac
    #utmcc
    #utmu
    should "properly track a page view" do
      tracker = Satellite.get_tracker(:google_analytics, {
          :utms => 1,
          #:utmn => 123456789, autogenerated
          :utmhn => 'api.mymobai.com',
          :utme => '5(controller*action*coupon_redeem)(10)8(test)9(Please_track_this)11(1)',
          :utmcn => 1,
          :utmcs => 'UTF-8',
          :utmsr => '1440x900',
          :utmul => 'de',
          :utmje => '1',
          :utmfl => '10.3%20r183',
          :utmdt => 'Properly track a page view',
          #:utmhid => '1655425535', auto
          :utmr => 'test.local/properly track a page view',
          :utmp => '/test/properly-track-page-view',
          :utmac => GOOGLE_ACCOUNT_ID
      })
      
      assert_equal tracker.track_page_view, true
    end
  end
end
